version: '3.9'

services:
  web:
    build: .
    container_name: sirius-django
    command: /app/entrypoint.sh
    volumes:
      - ./project:/app/project
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=root
    restart: unless-stopped 