# Generated by Django 4.2.7 on 2025-07-11 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/places/', verbose_name='Photo')),
                ('category', models.CharField(blank=True, choices=[('Museum', 'Музеи'), ('Cafe', 'Кафе'), ('Restaurant', 'Рестораны'), ('Monument', 'Памятники'), ('Shopping', 'Торговые центры'), ('Theater', 'Театры'), ('Cinema', 'Кинотеатры'), ('Gallery', 'Галереи'), ('Hotel', 'Отели'), ('Church', 'Храмы'), ('Other', 'Другие места')], default='Other', max_length=255, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Ужасно'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='core_place_name_113002_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['address'], name='core_place_address_9b34a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='valid_rating_range'),
        ),
    ]
