# Generated by Django 4.2.7 on 2025-07-11 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_place_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Lng'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('Museum', 'Музеи'), ('Cafe', 'Кафе'), ('Restaurant', 'Рестораны'), ('Monument', 'Памятники'), ('Shopping', 'Торговые центры'), ('Theater', 'Театры'), ('Cinema', 'Кинотеатры'), ('Gallery', 'Галереи'), ('Hotel', 'Отели'), ('Other', 'Другие места')], default='Other', max_length=255, null=True, verbose_name='Category'),
        ),
    ]
